### ISSUE TITLE
Unexpected error; please check your settings and try again

### ISSUE THREAD

**Issue by electricessence** [seansfkelley/synology-download-manager#61] opened 2017-12-30 00:44 UTC
### Versions

**Extension version**: 0.4.1

**Browser and version**: Firefox 57.0.3 (64-bit)

**DSM version**: DSM 6.1.4-15217 Update 5

**Download Station version**: 3.8.7-3490

### Steps to Reproduce the Issue

1) Try right-click downloading something. (a zip file for example).
```Unexpected error; please check your settings and try again```

### Expected Behavior

a) It works.

or 

b) It has a better explanation as to why.  Currently, I have no idea how to proceed to fix the problem since my credentials seem fine, and apparently if I try to manually add a URL I can select a destination without issue, but still fails to download.

**Comment by seansfkelley** [comment] 2017-12-30 16:29
Hm, that message only occurs on really severe failures. Those are not yet surfaced in the UI, but I've just filed #63 to track including it somewhere accessible.

If you want to dig a little more to help me debug this particular issue, you can find out what the exact error is with these steps:

1. Open a new tab with `about:debugging` and "Enable add-on debugging" (near the top).
2. Find Synology Download Manager in the list and hit "Debug" on it, which will open a new debugging window.
3. Switch to the Console tab in that window (along the top), and if it's got stuff in it I suggest you clear it (trash can icon on the top left) because it accumulates logging from every open tab (for some reason).
4. Reproduce the issue.
5. You should see a log line starting with `unexpected error while trying to add a download task`, followed by the error itself.

**Comment by electricessence** [comment] 2017-12-30 16:33
Investigating now.

**Comment by electricessence** [comment] 2017-12-30 16:36
unexpected error while trying to add a download task
```
Error: Request failed with status code 403
Stack trace:
createError@moz-extension://f7ee2d04-0b03-498b-9d3d-74b826168972/dist/js/background.js:2849:15
settle@moz-extension://f7ee2d04-0b03-498b-9d3d-74b826168972/dist/js/background.js:2866:12
handleLoad@moz-extension://f7ee2d04-0b03-498b-9d3d-74b826168972/dist/js/background.js:3193:7
```

**Comment by electricessence** [comment] 2017-12-30 16:40
Ok so 403 Unauthorized.  That's helpful almost.
I don't want to use my admin account for access to Download Station so I created a "Downloader" account with very limited access.  But like I said, it will show the list of possible folders if I try to paste a link in to the add dialog.  Same error though.

Is there some permissions change I need to make?

**Comment by seansfkelley** [comment] 2017-12-30 16:47
I believe the 403 is actually referring to the extension probing the link you're trying to download (to see if it's a .torrent file, for instance), not the permissions on the Synology account. If you try to download the link directly to your local machine instead, I would expect you to see the same issue. Do you?

I've filed #64 now to try to report these types of errors more helpfully as they seem like they'd be somewhat common.

**Comment by electricessence** [comment] 2017-12-30 16:49
It's a zip file.  Download Station can do standard downloads just fine.  Are you saying it has to be a torrent? :(

**Comment by seansfkelley** [comment] 2017-12-30 17:02
No, but it's conceivable that the link is pointing to (say) another site that you haven't logged into, and when the extension tries to see if it's a .torrent the site throws a 403 back at it. (Torrents have to be handled differently than direct-download files, which is why it probes the link before deciding what to do.)

The way this is implemented in the extension, it _should_ still happen if you try to download the link in question directly to your local machine, as it hasn't reached the part of the process where it needs to talk to the Synology yet. I say "should" because the extension doesn't want to actually download the file, so it uses slightly different (simpler, faster) types of requests than the browser would use to actually download the file. It's possible that the server (e.g.) blocks those requests, though that would be surprising.

Of course, this is all assuming that my theory about the 403 coming from the site and not the Synology is correct; the logging you provided above is silent on this point. However, I've never seen a 403 from a Synology before, and they have other methods of communicating "unauthorized" so I wouldn't expect to see it.

**Comment by electricessence** [comment] 2017-12-31 02:33
I can right click "Save Link As..." without issue.

**Comment by seansfkelley** [comment] 2017-12-31 04:49
Hm, that's unexpected. I don't know of a way to get more details in the current version, so I'll have to revisit once #63 exists.

**Comment by seansfkelley** [comment] 2018-03-31 03:51
Hey @electricessence, I finally got around to pushing a version that has better debugging capabilities. If you update to version 0.5.2 (just released) and still see this issue, it should produce a "debugging" section at the bottom of the settings page. Could you try to reproduce the issue and send that over?

**Comment by electricessence** [comment] 2018-03-31 20:44
:( I uninstalled and have since not been using it. :(

**Comment by seansfkelley** [comment] 2018-03-31 20:47
Oh, that's unfortunate. Well, if you decide to try it again and still see this issue, let me know. Until then, I'm going to close this out since I can't reproduce it.

**Closed by seansfkelley** 2018-03-31 20:47 UTC
