### ISSUE TITLE
extension logs out browser tabs or replaces the logged-in user with the one from the extension

### ISSUE THREAD

**Issue by Neoyoyo** [seansfkelley/synology-download-manager#175] opened 2021-03-06 13:10 UTC
## current status (maintainer edit)

This appears to be an unannounced change/breakage on Synology's part. I have a support ticket open with them now and will post any updates/next steps here. The workaround is to use the same user for the extension as for your normal browser tabs.

### Description

Since the update of DSM to version 6.2.4-25554 (on 2021-02-23), if Synology Download Manager is installed there are 2 typex of issues :

- when openning the URL to DSM, the user configured in Synology Download Manager is automatically logged on,
- the others users can't stay logged (even administrators accounts), having pop-up saying "user don't have enought privileges to do this action".

### Steps to Reproduce the Issue

1. Install DSM v6.2.4-25554 on the NAS ;
2. Install Synology Download Manager v0.9.3 in Firefox or Edge and configure it with user account.

### Failure Logs

No error in Synology Download Manager, only the behaviour of DSM.

### Versions

**Extension version** : 0.9.3

**Browser version** : Firefox 86.0

**DSM version** : 6.2.4-25554

**Download Station version** : 3.8.15.3563

**Comment by seansfkelley** [comment] 2021-03-12 08:05
This sounds like a duplicate of #32, except that that specifically affects DSM versions 5 and below.

Can you try using "Test Connection and Save" in the settings page? It will reset your login session, which could fix the problem. It should also state if it had to use the old login method with a link to issue #32, though I would not expect that to happen for DSM 6.

**Comment by Neoyoyo** [comment] 2021-03-12 13:22
Hello,
before creating this new issue, I had tested the uninstallation and then the reinstallation of the addon. Without success.
I just tested again with the "Test Connection and Save" function but the result is the same.

**Comment by seansfkelley** [comment] 2021-03-12 20:39
Thanks for confirming that. It After you tested the connection, it didn't say anything like "connection successful, but may interfere with existing login sessions"?

I'm away from my NAS now for upwards of a month, so unfortunately I won't be able to test and fix this until I'm back. Until then, I can only recommend the workarounds outlined in #32.

**Comment by Neoyoyo** [comment] 2021-03-13 13:11
Hi,
I confirm, no message such "connection successful, but may interfere with existing login sessions" at connection's test.
As a workaround I use another browser for the NAS' administration so don't worry :-)

**Comment by gvilloresi** [comment] 2021-03-26 03:14
I am having exactly the same issue.
Clearing browser's cache, cookies and using "Test Connection and Save" in the settings page didn't help.

**Comment by seansfkelley** [comment] 2021-03-27 06:16
@gvilloresi can you provide the versions of Download Station/Synology Download Manager/browser/DSM you're using?

**Comment by gvilloresi** [comment] 2021-04-01 01:44
@seansfkelley 
Thank you for replying. Here are the versions:
Download Station 3.8.16-3566
Synology Download Manager 0.9.3
Firefox 87.0
DSM 6.2.4-25556

Since I am not getting any update notifications, I suppose all of them are currently the latest versions.

**Comment by seansfkelley** [comment] 2021-04-01 05:41
Thank you, that's helpful. But unfortunately I still don't have access to my NAS to take a look myself, so for the time being you'll have to use a workaround.

**Comment by seansfkelley** [comment] 2021-04-10 02:13
I just saw this happen myself, but I don't have time to investigate further yet.

Repro steps to try:

1. Added a second copy of the extension in debug mode.
2. Log in second copy using the same creds as first copy (call them "A"). This second copy is slightly modified to skip downloading the .torrent file locally.
3. Log in with a browser tab using creds A.
4. Log out, then log in a browser tab using admin creds B.
5. Log out, then log in a browser tab using admin creds C.
6. Add a .torrent download with the right-click menu for the second copy.
7. Open the second copy's popup menu and watch the torrent for a bit.
8. Hopefully, the tab has been logged out.

**Comment by huettenwirt** [comment] 2021-04-21 06:39
Same here. I was searching for a while to find the connection to this extension, but I'm having the same issue of being logged out even as admin on my DSM 6.2.4-25556.

Would be great if you could find a solution to this! 
Thank you in advance for your great support and best regards!

**Comment by seansfkelley** [comment] 2021-04-26 00:01
This should be fixed by version 0.10.0 that I just published.

If you're using Firefox, you should be able to update right now.

If you're using Chrome, I don't know when Google will approve the changes, but watch for any updates there.

**Closed by seansfkelley** 2021-04-26 00:01 UTC
Labels: bug
