### ISSUE TITLE
Error: Broken link with torrent URL's

### ISSUE THREAD

**Issue by fadywar** [seansfkelley/synology-download-manager#30] opened 2017-10-02 18:07 UTC
Hi,

Does anyone have the issue that the plugin doesn't download torrents files?
It gives the error "Broken link", while the " Synology Download Station" plugin in Chrome works fine with the same torrent file?

Thank you.

**Comment by seansfkelley** [comment] 2017-10-15 19:31
I haven't seen that problem before. A few questions to help debug:

- What version of the extension do you have?
- Is the task successfully "added", and then it appears as "error - broken link" in the list of downloads, or does it never add the task at all?
- Which Chrome plugin are you using? If it's not this one, what happens if you use this one (https://chrome.google.com/webstore/detail/synology-download-manager/iaijiochiiocodhamehbpmdlobhgghgi) ?

**Comment by seansfkelley** [comment] 2017-11-16 00:18
I'm closing this due to a lack of reproducibility, but if you are still seeing the issue in the newest version of the extension (as of yesterday), please comment here and let me know!

**Closed by seansfkelley** 2017-11-16 00:18 UTC
