### ISSUE TITLE
can't log in with DSM 4.2

### ISSUE THREAD

**Issue by hoyeung3407** [seansfkelley/synology-download-manager#51] opened 2017-11-18 09:43 UTC
### Versions
**Extension version**: 0.30 or 0.31, last updated 2017-11-15
**Browser and version**: Firefox 56.0 (64 bit)
**DSM version**: 4.2-3256
**Download Station version**: 3.3-2386

### Steps to Reproduce the Issue

It just stop working some days ago, 
today i open the settings page and click the "Test Connection" button, 
then it shows "The requested version does not support this functionality."

Please bring back support for old DSM in future versions, thank you.

**Comment by seansfkelley** [comment] 2017-11-18 20:30
Oh boy. Given that this happens with "test connection", this must have been caused by the fix to https://github.com/seansfkelley/synology-download-manager/issues/32, which increased the API version used for logging in to prevent it from overriding the browser's session cookies.

It seems reasonable to reintroduce this to support old versions, with a caveat. I'm thinking:

- `synology-typescript-api` should accept a version parameter for the API calls
- The extension should check if the NAS supports a sufficient version of the auth API. If it does, change nothing. If it doesn't, drop down to using the old API version but warn the user (probably with a link to https://github.com/seansfkelley/synology-download-manager/issues/32).

Auditing `synology-typescript-api` for usages of `version !== 1` will likely help prevent these issues in the future.

**Comment by hoyeung3407** [comment] 2017-11-19 02:57
It seems to be the solution, hope it is acceptable for other users too.
Thank you very much !

**Comment by seansfkelley** [comment] 2017-11-19 21:21
@hoyeung3407 in the mean time, you can use [version 0.2.1](https://addons.mozilla.org/en-US/firefox/addon/synology-download-manager/versions/?page=1#version-0.2.1) which shouldn't have this issue (though also with fewer features). I'm hoping to get a fix out in the next couple days!

**Comment by hoyeung3407** [comment] 2017-11-20 02:55
Oh, you're really helpful. Thank you.

**Comment by seansfkelley** [comment] 2017-11-20 06:47
Should be fixed by 6df62e8da0f4759b05cadab1174ee5d837e3bc48.

**Closed by seansfkelley** 2017-11-20 06:47 UTC

**Comment by hoyeung3407** [comment] 2017-11-20 07:32
You're a lifesaver ! 
Updated to version 0.4.1 and it works again. 
Very quick response and update, thank you !

**Comment by seansfkelley** [comment] 2017-11-20 19:03
Yay! Thanks for verifying for me.
