### ISSUE TITLE
Unknown error displaying task

### ISSUE THREAD

**Issue by valjeanchan** [seansfkelley/synology-download-manager#80] opened 2018-03-29 13:43 UTC
Redacted extension state: {
  "lastSevereError": "(omitted for brevity)",
  "connection": {
    "protocol": "https",
    "hostname": true,
    "port": true,
    "username": true,
    "password": true
  },
  "visibleTasks": {
    "downloading": true,
    "uploading": true,
    "completed": true,
    "errored": true,
    "other": true
  },
  "notifications": {
    "enableFeedbackNotifications": true,
    "enableCompletionNotifications": false,
    "completionPollingInterval": 60
  },
  "tasks": 1,
  "taskFetchFailureReason": null,
  "tasksLastInitiatedFetchTimestamp": 1522330951900,
  "tasksLastCompletedFetchTimestamp": 1522330952094,
  "stateVersion": 2
}

Error: 'never assertion failed, got value undefined'
Error stack trace: assertNever@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:25132:11
sortTasks@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:29123:20
renderTaskList@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:30072:114
render@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:29978:17
finishClassComponent@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:10727:22
updateClassComponent@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:10704:12
beginWork@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:11079:16
performUnitOfWork@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:13078:16
workLoop@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:13142:26
callCallback@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:3396:9
invokeGuardedCallbackDev@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:3435:7
invokeGuardedCallback@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:3292:5
renderRoot@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:13220:7
performWorkOnRoot@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:13868:24
performWork@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:13821:7
requestWork@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:13732:7
scheduleWorkImpl@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:13586:11
scheduleWork@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:13543:12
scheduleTopLevelUpdate@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:14047:5
updateContainer@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:14085:7
renderSubtreeIntoContainer/<@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:18080:7
unbatchedUpdates@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:13956:12
renderSubtreeIntoContainer@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:18079:5
render@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:18144:12
@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:30175:13
fetchStateAndNotify/</<@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:28206:32
fetchStateAndNotify/<@moz-extension://3d47fa07-f5e8-4b7a-9ce8-fd6f6f4017bd/dist/js/popup.js:28206:9

React stack trace:
    in Popup
    in FatalErrorWrapper

**Comment by seansfkelley** [comment] 2018-03-29 15:06
Duplicate of #78. I should have a fix in the next few days; if you want to fix the issue right now unfortunately the only way is to uninstall and reinstall the extension.

**Closed by seansfkelley** 2018-03-29 15:06 UTC
