### ISSUE TITLE
[feature request] Save file to Synology

### ISSUE THREAD

**Issue by Xinnony** [seansfkelley/synology-download-manager#74] opened 2018-03-17 22:00 UTC
Hi, i have idea,
Is add in the "Save file to" popup to save to Synology, see this exemple:

![image](https://user-images.githubusercontent.com/6058403/37560283-b3668db4-2a35-11e8-999b-48a256e201e2.png)

Reference: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Working_with_files

**Comment by seansfkelley** [comment] 2018-03-19 00:15
Thanks for the suggestion! I think this is a duplicate of #45.

**Closed by seansfkelley** 2018-03-19 00:15 UTC
