### ISSUE TITLE
Conflicts with WordPress log in

### ISSUE THREAD

**Issue by LeopardPagan** [seansfkelley/synology-download-manager#173] opened 2021-02-20 09:55 UTC
Been a great plug in for the last couple of years on FFox. 2 weeks ago I setup WordPress for the 1st time hosted by FastHost UK & found I could not log in to the dashboard.
All i got was a blank screen & eventually a time out message. 
Dashboard log in was fine on other browsers, I then started working my way through the plugins in FFox. 
Disabled all,page refresh & log in appeared.
I enabled each plugin (only have 3) till the log in page went blank & sadly that was the Synology Download Manager plugin. :(
Hope you find a way to fix this as had to revert back to the old way of adding Torrents to Download station.

**Comment by seansfkelley** [comment] 2021-02-20 22:20
Thank you for the detailed bug report. This is strange behavior; this extension does inject a small amount of code into each page to detect magnet link clicks but it should be well isolated.

You can help me debug with a few things:

- When testing your various extensions, did test each one individually? It's possible that there's a bad interaction between this extension and another extension instead of between this extension and the page itself. What are the other two extensions?
- Is there anything shown in the debug logs in the settings page of this extension? It'll be at the bottom of the settings page and quite obviously for debugging purposes.
- Can you send me the content of the browser console for the broken page? You can get to it via Tools > Web Developer > Web Console when looking at the broken page. Make sure to scrub any private information that sometimes appears there.

Thanks in advance!

**Comment by seansfkelley** [comment] 2021-03-18 22:48
Hi @LeopardPagan, can you answer some of the questions above?

Can you also provide the versions for the extension, browser, and DSM? That'll help me reproduce the issue.

**Comment by seansfkelley** [comment] 2021-04-10 02:11
Closing; cannot reproduce and no further information was provided.

**Closed by seansfkelley** 2021-04-10 02:11 UTC
Labels: bug
