### ISSUE TITLE
[bug] Huge memory usage with lots of downloads

### ISSUE THREAD

**Issue by ntucker** [seansfkelley/synology-download-manager#93] opened 2018-08-17 23:52 UTC
### Versions

**Extension version**: (visible in Synology Download Manager's settings (Firefox) or in the extension list (Chrome))
0.5.5 and before

**Browser and version**: (usually found in the browser's "About")
firefox 61.0.2

**DSM version**: (DSM > Control Panel > Info Center > General > DSM version)
DSM 6.2-23739 Update 2

**Download Station version**: (DSM > Package Center > Installed > Download Station > Installed version)
3.8.10-3509

### Steps to Reproduce the Issue

1. Have >1000 completed downloads in the download manager
2. either open the download list (even with completed things filtered out) -OR- start a new download
3. see memory usage skyrocket eating up 95-99% of all system memory on a 16gb machine

Note: I just deleted all completed tasks bring it down to only 5 pages of task and now when i start a new download or open the status it only increases memory by 1-2gigs (still pretty insane tho)

**Comment by seansfkelley** [comment] 2019-10-05 19:52
Hey @ntucker, since you filed this issue I've upgraded a bunch of tooling and fixed many small issues that that turned up. None of that was specifically intended to fix this memory issue (as I can't reproduce it), but I'm wondering if you still see this issue with the latest version of the extension.

**Comment by ntucker** [comment] 2019-10-06 23:44
I cleared most of my completed downloads and moved my machine to 64GB ram so I haven't been in the conditions to notice if it's still there.

**Comment by seansfkelley** [comment] 2019-10-08 15:14
Okay, thanks for the response. I'm going to close this out in that case.

**Closed by seansfkelley** 2019-10-08 15:14 UTC
Labels: bug
