### ISSUE TITLE
Unknown error displaying tasks on Firefox

### ISSUE THREAD

**Issue by jbbanegas** [seansfkelley/synology-download-manager#79] opened 2018-03-28 23:35 UTC
Error: 'never assertion failed, got value undefined'
Error stack trace: assertNever@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:25132:11
sortTasks@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:29059:20
renderTaskList@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:30006:114
render@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:29912:17
finishClassComponent@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:10727:22
updateClassComponent@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:10704:12
beginWork@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:11079:16
performUnitOfWork@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:13078:16
workLoop@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:13142:26
callCallback@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:3396:9
invokeGuardedCallbackDev@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:3435:7
invokeGuardedCallback@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:3292:5
renderRoot@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:13220:7
performWorkOnRoot@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:13868:24
performWork@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:13821:7
requestWork@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:13732:7
scheduleWorkImpl@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:13586:11
scheduleWork@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:13543:12
scheduleTopLevelUpdate@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:14047:5
updateContainer@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:14085:7
renderSubtreeIntoContainer/<@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:18080:7
unbatchedUpdates@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:13956:12
renderSubtreeIntoContainer@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:18079:5
render@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:18144:12
@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:30109:13
fetchStateAndNotify/</<@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:25653:32
fetchStateAndNotify/<@moz-extension://85d52261-38ba-4b36-b399-99e425e45d1f/dist/js/popup.js:25653:9

React stack trace:
    in Popup
    in FatalErrorWrapper

**Comment by seansfkelley** [comment] 2018-03-29 01:15
Duplicate of #78.

**Closed by seansfkelley** 2018-03-29 01:15 UTC
