### ISSUE TITLE
External url not accepted

### ISSUE THREAD

**Issue by AlexKalopsia** [seansfkelley/synology-download-manager#140] opened 2020-03-02 18:50 UTC
**Extension version**: 0.7.0

**Browser and version**: Firefox 73.0.1

**DSM version**: 6.2.2-24922 Update 4

**Download Station version**: 3.8.14-3543

### Failure Logs

```
Cannot find this :(
```

### Steps to Reproduce the Issue

1. Set host to external url (either http or hrrps)
2. Set correct port and user data
3. Connection failed. Likely cause: wrong hostname/port, no internet connection or invalid certificate 

This does not occur when I use the internal IP. If I visit the external url Firefox says that the certificate is perfectly fine.

**Comment by seansfkelley** [comment] 2020-03-02 20:15
I just confirmed that this does work as expected on my setup on the latest version of the extension too. This makes me think it's something about your setup.

However, you already pre-empted most of my questions (so thank you for the detailed report)! Two questions:

- Did this work in the past?
- Are you sure you have the right port when using the external URL? Are you doing any kind of port mapping on your router (for instance, 5001-> 443)?

The nuclear option is to remove the extension, restart the browser, and install it again. Network issues like this are... annoying. I'm wondering if a recent update or something has it confused about what certificates are allowed.

**Comment by seansfkelley** [comment] 2020-03-12 22:39
Ping @AlexKalopsia, are you still seeing issues?

**Comment by seansfkelley** [comment] 2020-04-02 17:30
Closing -- cannot reproduce.

**Closed by seansfkelley** 2020-04-02 17:30 UTC
